### ISSUE TITLE
bug with some Sasmung devices

### ISSUE THREAD

**Issue by aimiliano** [Yalantis/Phoenix#17]
i have copied your SunRefreshView and made my own with my own icons

in most of the devices is workin ok but in some samsung devices and some sony  i am getting this  error:

ava.lang.NullPointerException
at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1083)
at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:827)
at com.yalantis.phoenix.refresh_view.LoadingRefreshView.drawSun(LoadingRefreshView.java:213)
at com.yalantis.phoenix.refresh_view.LoadingRefreshView.draw(LoadingRefreshView.java:156)
at android.widget.ImageView.onDraw(ImageView.java:1040)
at android.view.View.draw(View.java:15400)
at android.view.View.getDisplayList(View.java:14294)
at android.view.View.getDisplayList(View.java:14336)
at android.view.View.draw(View.java:15114)
at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3162)
at android.view.View.draw(View.java:15403)
at android.view.View.getDisplayList(View.java:14294)
at android.view.View.getDisplayList(View.java:14336)
at android.view.View.draw(View.java:15114)
at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
at android.view.View.draw(View.java:15403)
at android.view.View.getDisplayList(View.java:14294)
at android.view.View.getDisplayList(View.java:14336)
at android.view.View.draw(View.java:15114)
at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
at android.view.View.draw(View.java:15403)
at android.support.v4.view.ViewPager.draw(ViewPager.java:2257)
at android.view.View.getDisplayList(View.java:14294)
at android.view.View.getDisplayList(View.java:14336)
at android.view.View.draw(View.java:15114)
at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
at android.view.View.getDisplayList(View.java:14289)
at android.view.View.getDisplayList(View.java:14336)
at android.view.View.draw(View.java:15114)
at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
at android.view.View.getDisplayList(View.java:14289)
at android.view.View.getDisplayList(View.java:14336)
at android.view.View.draw(View.java:15114)
at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
at android.view.View.getDisplayList(View.java:14289)
at android.view.View.getDisplayList(View.java:14336)
at android.view.View.draw(View.java:15114)
at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
at android.view.View.getDisplayList(View.java:14289)
at android.view.View.getDisplayList(View.java:14336)
at android.view.View.draw(View.java:15114)
at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
at android.view.View.draw(View.java:15403)
at android.widget.FrameLayout.draw(FrameLayout.java:472)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2583)
at android.view.View.getDisplayList(View.java:14294)
at android.view.View.getDisplayList(View.java:14336)
at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1585)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1457)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2779)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2645)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2213)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6632)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
at android.view.Choreographer.doCallbacks(Choreographer.java:613)
at android.view.Choreographer.doFrame(Choreographer.java:583)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5598)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)

**Comment by shliama** [comment]
well, with all my magic powers I cannot guess the problem...
Either files (that you are using) or repo with your code (if it's private, create sample project based on my sample, with your icons) are needed so I can see what's the problem.

p.s. as I see, it crashes when tries to draw sun, so take a good look at that image, maybe try to export it into another image format, or reduce size/quality a lil...
