### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by brucelam** [Yalantis/Phoenix#43]
java.lang.OutOfMemoryError: 
  at android.graphics.Bitmap.nativeCreate(Native Method:0)
  at android.graphics.Bitmap.createBitmap(Bitmap.java:922)
  at android.graphics.Bitmap.createBitmap(Bitmap.java:895)
  at android.graphics.Bitmap.createBitmap(Bitmap.java:827)
  at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:703)
  at com.yalantis.phoenix.refresh_view.SunRefreshView.createBitmaps(SunRefreshView.java:110)
  at com.yalantis.phoenix.refresh_view.SunRefreshView.initiateDimens(SunRefreshView.java:102)
  at com.yalantis.phoenix.refresh_view.SunRefreshView$1.run(SunRefreshView.java:79)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5433)
  at java.lang.reflect.Method.invokeNative(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
  at dalvik.system.NativeStart.main(Native Method:0)

**Comment by ArcherEmiya05** [comment]
Getting the same issue, any solution? Thanks
